- name: Build with our Docker image
  run: |
    docker run --rm -v "${{ github.workspace }}:/src" ghcr.io/koman10/guardian-beacon:latest bash -lc '
      set -eux
      cd /src

      echo "== Building firmware inside container =="

      if [ -f scripts/build.sh ]; then
        ./scripts/build.sh -t pinetime -r
      else
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DARM_NONE_EABI_TOOLCHAIN_PATH=/opt/gcc-arm-none-eabi-10.3-2021.10
        cmake --build build -j"$(nproc)"
      fi

      echo "== Build complete =="
      ls -lh build || true
      ls -lh build/*.bin build/*.hex 2>/dev/null || true
    '
