name: Build firmware (Guardian Beacon)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/workflows/docker.yml"
      - "README.md"

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install toolchain & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build cmake python3 git \
            gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Show tree (debug)
        run: |
          git submodule status || true
          ls -la
          ls -la scripts || true
          cmake --version
          arm-none-eabi-gcc --version
          ninja --version

      - name: Build (prefer InfiniTime script)
        shell: bash
        run: |
          set -eux
          if [ -f scripts/build.sh ]; then
            chmod +x scripts/build.sh || true
            ./scripts/build.sh -t pinetime -r
          else
            cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
            cmake --build build -j"$(nproc)"
          fi

      - name: List build outputs
        run: |
          echo "== build dir =="
          ls -lh build || true
          echo "== bin/hex/zip =="
          ls -lh build/**/*.bin build/**/*.hex build/**/*.zip 2>/dev/null || true

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: guardian-firmware
          path: |
            build/**/*.bin
            build/**/*.hex
            build/**/*.zip
            build/**/*.out
          if-no-files-found: warn
